AWSTemplateFormatVersion: 2010-09-09

Description: Create for IPSet


Resources:
#アクセスを拒否するIPアドレスの設定,テストで自分のIPアドレスが入っている範囲を指定してみる
  MyIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Addresses: 
        - 192.168.0.0/32
      Description: "Test the block of IP address"
      IPAddressVersion: IPV4
      Name: MyIPSet
      Scope: REGIONAL
      
Outputs:

  MyIPSet:
    Value: !GetAtt MyIPSet.Arn
    Export:
      Name:  MyIPSet-Arn
