AWSTemplateFormatVersion: 2010-09-09

Description: Create WAF of ALB

Parameters: 
  NameBase:
    Description: this is base name.
    Type: String
    Default:  RaiseTech

Resources:
  
  WAFRuleGroup:
    Type: AWS::WAFv2::RuleGroup
    Properties: 
      Name: SampleRuleGroup
      Scope: REGIONAL
      Capacity: 1000
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        SampledRequestsEnabled: true
        MetricName: MyRuleGroupMetrics
      Rules:
        - Name: rbrNoCustomKeys
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 1000                    #１つのIPアドレスから５分間に1000回以上のリクエストがきたらブロックする設定
              AggregateKeyType: FORWARDED_IP
              ForwardedIPConfig:
                HeaderName: X-Forwarded-For  #X-Forwarded-ForというHTTPヘッダーを使ってIPアドレスを集計するコードらしい
                FallbackBehavior: MATCH      #X-Forwarded-ForヘッダーがなくてもソースIPをそのまま使ってルールを適応する
          Action:                          #ロードバランサーやプロキシを通過していなくてもクライアントの実際のIPIPをもとにしてルールを適応する
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true   
            CloudWatchMetricsEnabled: true 
            MetricName: RateLimitExceeded


  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Scope: REGIONAL #ここはCLOUDFRONTかの二択、CloudForntかリージョン内のALBなどのリソースか
      VisibilityConfig:
        CloudWatchMetricsEnabled: true #CloudWatchにメトリクスを送るかどうか
        MetricName: !Sub "${NameBase}-MyWebACL"
        SampledRequestsEnabled: true   #ルールが一致したリクエストをサンプルとして保存するかどうか
      

  WebACLAssociation:                      #WAFとALBの関連付け
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !ImportValue ALBArnExport
      WebACLArn: !GetAtt WebACL.Arn
