version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-cloudformation: orbss/aws-cloudformation@0.1.6
  ansible-playbook: orbss/ansible-playbook@0.0.5

deploy:
    docker:
      - image: cimg/python:3.11.0
  
jobs:
  cfn-lint:
    docker:
      - image: cimg/python:3.11.0
    steps:
      - checkout
      - run: python --version
      - run: pip install --upgrade pip
      - run: pip --version
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml

  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run:
          name: cloudformation deploy
          command: |
            set -x 
            aws cloudformation deploy --template-file cloudformation/VPC.yml --stack-name circleci-test-VPC
            aws cloudformation deploy --template-file cloudformation/EC2-RDS.yml --stack-name circleci-test-EC2-RDS --capabilities CAPABILITY_NAMED_IAM
            aws cloudformation deploy --template-file cloudformation/S3.yml --stack-name circleci-test-S3 --capabilities CAPABILITY_NAMED_IAM
  execute-ansible:
    executor: ansible-playbook/default
    docker:
      - image: cimg/python:2.7
    steps:
      - checkout
      - run:
          name: python -m pip install --upgrade pip
          command: python -m pip install --force-reinstall --upgrade pip
      - add_ssh_keys: 
          fingerprints:
            - SHA256:z6G5uUi9DsBbxk/aZ16M3ZjLEcZlKCeurc1XD88gndw
      - run: 
          name: install ansible
          command: pip install ansible==2.10.7
      - run:
          name: Install community.mysql collection
          command: |
            ansible-galaxy collection install community.mysql -vvv
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: '-u ec2-user -i ansible/inventory --private-key  ~/AWS-access/lecture13.pem'
workflows:
  raisetech:
    jobs:
      - cfn-lint
      - execute-cloudformation
      - execute-ansible:
          requires:
            - execute-cloudformation

